name: Deploy
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Compile and build classes
        run: ./gradlew classes
      - name: Run code checks
        run: ./gradlew check
      - name: Run unit tests
        run: ./gradlew --no-build-cache cleanTest test
      - name: build jar
        continue-on-error: true
        run: ./gradlew dist
      - name: Upload JAR
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            game/desktop/build/libs/desktop-1.0.jar
  upload-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: consolidate deploy folder
        run: |
          mkdir deploy
          mv game/desktop/build/libs/desktop-1.0.jar deploy
      - name: Upload binaries to GitHub Release
        continue-on-error: true
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          prerelease: true
          overwrite: true
          file_glob: true
          body: |
            ## ${{ github.ref_name }}
            
            ${{ github.event.head_commit.message }}